### ISSUE TITLE
Please Share the  Check points weights for  cvt13. 

### ISSUE THREAD

**Issue by abdulhaseeb2k** [Dmmm1997/DenseUAV#5]
**FILE Backbone.py**
____________________________________________________       
        elif backbone=="cvt13":
            backbone_model, channels = get_cvt_models(model_size="cvt13")
            output_channel = channels[-1]
            checkpoint_weight = **"/home/dmmm/VscodeProject/FPI/pretrain_model/CvT-13-384x384-IN-22k.pth"**
 _____________________
I tried to find  it on your domain, "https://zhuanlan.zhihu.com/p/676420788" and hugging Face but unfortunately  i didn't get it.
____________________

**Comment by Dmmm1997** [comment]
Hi，
please download it from the official repo: https://github.com/microsoft/CvT

**Comment by abdulhaseeb2k** [comment]
Thanku so much dear
