### ISSUE TITLE
txt文件标注问题

### ISSUE THREAD

**Issue by msyoyozhang** [Dmmm1997/DenseUAV#6]
├── DenseUAV/
│   ├── Dense_GPS_ALL.txt           /* format as: path latitude longitude height
│   ├── Dense_GPS_test.txt
│   ├── Dense_GPS_train.txt

想请问一下txt文件中的高度是指无人机距地面高度吗

**Comment by Dmmm1997** [comment]
是的

**Comment by Dmmm1997** [comment]
> ├── DenseUAV/ │ ├── Dense_GPS_ALL.txt /* format as: path latitude longitude height │ ├── Dense_GPS_test.txt │ ├── Dense_GPS_train.txt
> 
> 想请问一下txt文件中的高度是指无人机距地面高度吗

是的

**Comment by msyoyozhang** [comment]
好的，谢谢您的回复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Dmmm1997/DenseUAV"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月30日(星期四) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Dmmm1997/DenseUAV] txt文件标注问题 (Issue #6)





  
├── DenseUAV/ │ ├── Dense_GPS_ALL.txt /* format as: path latitude longitude height │ ├── Dense_GPS_test.txt │ ├── Dense_GPS_train.txt
 
想请问一下txt文件中的高度是指无人机距地面高度吗
  
是的
